### ISSUE TITLE
Consider making left operand of -> optional

### ISSUE THREAD

**Issue by allenwb** [zenparsing/js-classes-1.1#17]
@BrendanEich said: "The this-> is tedious and cries out for shorthand."

We could make `this` on the left of -> optional by adding a production like to the grammar:

_PrimaryExpression_ : **->** _IdentifierName_

However, that by itself would introduce an ASI hazard:
```js
class C {
  var x, y
  constructor(a, b) {
    ->x = a   /* ASI hazard */
    ->y = b
  }
}
```
This can be eliminate by adding a line terminator restriction to: 
_MemberExpression_ : _MemberExpression_ [no _LineTerminator_ here]  **->** _IdentifierName_
_CallExpression_ : _CallExpression_ [no _LineTerminator_ here]  **->** _IdentifierName_

This is consistent with how similar ASI hazard are already handled.

**Comment by wycats** [comment]
> @allenwb yes, Self's name rationale is another bit of quasi-evidence that this->, like self. before it, is too long for the common case. If TC39 will insist on a shorthand, then we should add one to this proposal, somehow, to avoid bouncing.

Notably, Ruby, the main other Smalltalk descendant, **also** made `self` optional in `self.foo()`, and also has an instance variable shorthand of the form `@foo` and `@foo = expr`.

In the status quo proposal, I agreed to separate the shorthand into its own proposal because I didn't think it was in conflict with the rest of the proposal, and didn't think the rest of the proposal significantly foreclosed the shorthand.

I still feel strongly that we should eventually consider the shorthand again, and disappointed that this proposal seems less of a good fit for a shorthand (for the standard.js hostility reason Kevin raised in this thread and the confusion with lexical scoping raised in #17).

In addition to the issues already raised in this thread, I find `->x` to be a less suitable shorthand than Ruby's `@foo` or the previously proposed `#foo`.
